version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products_db
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./api
    container_name: backend-container
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - db
    volumes:
      - ./api:/app

  frontend:
    build: ./Front
    container_name: frontend-container
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./Front:/app

volumes:
  db_data:
