version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
